### ISSUE TITLE
Not Working with Shows.

### ISSUE THREAD

**Issue by Arturoe1** [mikenye/docker-plex_dupefinder#2]
Installed and being able to run. 
Check Movies all fine. When it comes to the shows this error is thrown, like this is an old plex_dupefinder version with no access to find dupes in Shows. 

> Initialized
Finding dupes...
Found 0 dupes for section 'Movies'
Traceback (most recent call last):
  File "/usr/local/bin/plex_dupefinder", line 354, in <module>
    dupes = get_dupes(section)
  File "/usr/local/bin/plex_dupefinder", line 52, in get_dupes
    dupe_search_results = plex.library.section(plex_section_name).search(duplicate=True, libtype=sec_type)
  File "/usr/lib/python3.8/site-packages/plexapi/library.py", line 668, in search
    args[category] = self._cleanSearchFilter(category, value, libtype)
  File "/usr/lib/python3.8/site-packages/plexapi/library.py", line 717, in _cleanSearchFilter
    raise BadRequest('Unknown filter category: %s' % category)
plexapi.exceptions.BadRequest: Unknown filter category: duplicate
[cmd] /usr/local/bin/plex_dupefinder exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-plex_dupefinder: executing...
[cont-finish.d] 99-plex_dupefinder: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

The Linux version from l3uddz works correctly, it finds the dupes in Shows library.

> Initialized
Finding dupes...
Found 0 dupes for section 'Movies'
Found 6 dupes for section 'TV'
Which media item do you wish to keep for

**Comment by mikenye** [comment]
It looks like there's a bug in python-plexapi, introduced in new versions of Plex.

https://github.com/pkkid/python-plexapi/issues/595

I'm afraid we'll have to wait for a fix.

**Comment by Arturoe1** [comment]
Thank you the info!
We will have to wait, for the moment the linux seems to work to it is fine. 

Thank you again for your support.

**Comment by mikenye** [comment]
No problems. You’re very welcome. :-)

**Comment by mikenye** [comment]
This should now, finally, be resolved. Thanks for your patience.
